name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: soojinpark.co.kr
          username: ubuntu
          key: ${{ secrets.EC2_KEY }}
          script: |
            cd ~
            ./deploy.sh
          timeout: "300s"
          command_timeout: "10m"
          request_pty: true
